# Generated by Django 4.2.23 on 2025-07-16 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('JEE+NEET', 'JEE+NEET')], max_length=20)),
                ('batch', models.CharField(max_length=50)),
                ('course_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(blank=True, max_length=255, null=True)),
                ('option_b', models.CharField(blank=True, max_length=255, null=True)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('question_type', models.CharField(choices=[('numerical', 'Numerical'), ('option', 'Option')], max_length=20)),
                ('correct_answer_numerical_min', models.FloatField(blank=True, null=True)),
                ('correct_answer_numerical_max', models.FloatField(blank=True, null=True)),
                ('question_file', models.FileField(blank=True, null=True, upload_to=website.models.unique_upload_path)),
                ('option_a_file', models.FileField(blank=True, null=True, upload_to=website.models.unique_upload_path)),
                ('option_b_file', models.FileField(blank=True, null=True, upload_to=website.models.unique_upload_path)),
                ('option_c_file', models.FileField(blank=True, null=True, upload_to=website.models.unique_upload_path)),
                ('option_d_file', models.FileField(blank=True, null=True, upload_to=website.models.unique_upload_path)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('explanation_file', models.FileField(blank=True, null=True, upload_to=website.models.unique_upload_path)),
                ('marks_award', models.FloatField()),
                ('marks_deduct', models.FloatField()),
                ('tag', models.CharField(choices=[('AI generated', 'AI generated'), ('PYQ', 'PYQ'), ('Expected Question', 'Expected Question')], max_length=50)),
                ('visible', models.BooleanField(default=False)),
                ('chapter', models.ManyToManyField(related_name='questions', to='website.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Coordinator', 'Coordinator'), ('Tutor', 'Tutor')], max_length=50)),
                ('subject', models.CharField(choices=[('Overall', 'Overall'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('English', 'English'), ('Aptitude', 'Aptitude'), ('Web Development', 'Web Development'), ('Test and DPP', 'Test and DPP')], max_length=50)),
                ('quote', models.TextField(blank=True, null=True)),
                ('is_legacy', models.BooleanField(default=False, help_text='Check this for previous (legacy) members.')),
            ],
            options={
                'ordering': ['subject', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_number', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('administrator', 'Administrator')], default='student', max_length=20)),
                ('roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(max_length=50)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='website.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DurationField()),
                ('result_released', models.BooleanField(default=False)),
                ('accepting_response', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tests', to='website.userdata')),
                ('question_list', models.ManyToManyField(related_name='tests', to='website.question')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='website.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=website.models.unique_upload_path)),
                ('description', models.TextField()),
                ('type_of_material', models.CharField(choices=[('PDF', 'PDF'), ('YT', 'YT')], default='PDF', max_length=20)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('chapter', models.ManyToManyField(related_name='study_materials', to='website.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='website.subject'),
        ),
        migrations.CreateModel(
            name='TestSubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_response', models.JSONField(blank=True, null=True)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, default=0.0, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='website.test')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_submissions', to='website.userdata')),
            ],
            options={
                'unique_together': {('user_profile', 'test')},
            },
        ),
    ]
