# Generated by Django 4.2.23 on 2025-09-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='announcements/pdfs/'),
        ),
    ]
