# Generated by Django 4.2.23 on 2025-09-14 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_photo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='file',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='type_of_material',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='concept_name',
            field=models.CharField(default='Untitled Concept', max_length=255),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudyMaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='study_materials/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'Video'), ('OTHER', 'Other')], default='PDF', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='website.studymaterial')),
            ],
        ),
    ]
