# Generated by Django 4.2.23 on 2025-09-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_studymaterial_chapter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('NUM', 'Numerical'), ('MCQ', 'Multiple Choice')], max_length=3)),
                ('correct_integer', models.IntegerField(blank=True, null=True)),
                ('correct_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated choices for MCQ', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='play_question_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
