# Generated by Django 4.2.23 on 2025-09-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_playquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('NUM', 'Numerical'), ('MCQ', 'Multiple Choice')], max_length=3)),
                ('correct_integer', models.IntegerField(blank=True, null=True)),
                ('correct_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('choices', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mock_question_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('open_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_questions', models.ManyToManyField(blank=True, to='website.mockquestion')),
                ('play_questions', models.ManyToManyField(blank=True, to='website.playquestion')),
            ],
        ),
    ]
