# Generated by Django 4.2.23 on 2025-09-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_mockquestion_mocktest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mocktest',
            old_name='play_questions',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='mocktest',
            name='custom_questions',
        ),
        migrations.DeleteModel(
            name='MockQuestion',
        ),
        migrations.AddField(
            model_name='mocktest',
            name='custom_questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
