# Generated by Django 4.2.23 on 2025-09-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_play_questions_mocktest_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocktest',
            name='custom_questions',
        ),
        migrations.RemoveField(
            model_name='mocktest',
            name='questions',
        ),
        migrations.AddField(
            model_name='mocktest',
            name='play_questions',
            field=models.ManyToManyField(blank=True, related_name='mock_tests', to='website.playquestion'),
        ),
        migrations.CreateModel(
            name='MockTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('NUM', 'Numerical'), ('MCQ', 'Multiple Choice')], max_length=3)),
                ('correct_integer', models.IntegerField(blank=True, null=True)),
                ('correct_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated choices for MCQ', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mock_question_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mocktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='website.mocktest')),
            ],
        ),
    ]
