# Generated by Django 4.2.23 on 2025-09-15 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0014_testhistory_delete_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('play', 'Playmode'), ('mock', 'Mock'), ('subwise', 'Subwise'), ('bullet', 'Bullet'), ('blitz', 'Blitz'), ('survival', 'Survival')], max_length=20)),
                ('score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('time_taken', models.IntegerField(help_text='Time in seconds')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TestHistory',
        ),
    ]
