# Generated by Django 4.2.23 on 2025-09-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
