# Generated by Django 4.2.23 on 2025-09-18 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0021_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-taken_at']},
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='correct',
            new_name='total_possible_score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='wrong',
        ),
        migrations.AddField(
            model_name='testresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='unanswered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='mode',
            field=models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('survival', 'Survival'), ('subwise', 'Subwise'), ('mock', 'Mock Test')], max_length=20),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='time_taken',
            field=models.IntegerField(blank=True, help_text='Time in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
