# Generated by Django 4.2.23 on 2025-09-18 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0022_alter_testresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={},
        ),
        migrations.AlterField(
            model_name='testresult',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
