# Generated by Django 4.2.23 on 2025-09-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_testresult_options_alter_testresult_time_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='user',
        ),
    ]
