# Generated by Django 4.2.23 on 2025-09-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_usermessage_result_csv_alter_usermessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='duration_minutes',
            field=models.IntegerField(default=180, help_text='Duration of the mock test in minutes (e.g., 180 for 3 hours)'),
        ),
    ]
